/***
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Do not edit this file. It will be overwritten when the configure script is run.
 ***/

#ifndef CHAMPSIM_CONSTANTS_H
#define CHAMPSIM_CONSTANTS_H
#include <cstdlib>
#include "util.h"
constexpr unsigned BLOCK_SIZE = 64;
constexpr unsigned PAGE_SIZE = 4096;
constexpr uint64_t STAT_PRINTING_PERIOD = 10000000;
constexpr std::size_t NUM_CPUS = 1;
constexpr auto LOG2_BLOCK_SIZE = champsim::lg2(BLOCK_SIZE);
constexpr auto LOG2_PAGE_SIZE = champsim::lg2(PAGE_SIZE);
constexpr uint64_t DRAM_IO_FREQ = 3200;
constexpr std::size_t DRAM_CHANNELS = 1;
constexpr std::size_t DRAM_RANKS = 1;
constexpr std::size_t DRAM_BANKS = 8;
constexpr std::size_t DRAM_ROWS = 65536;
constexpr std::size_t DRAM_COLUMNS = 128;
constexpr std::size_t DRAM_CHANNEL_WIDTH = 8;
constexpr std::size_t DRAM_WQ_SIZE = 64;
constexpr std::size_t DRAM_RQ_SIZE = 64;
#endif